### ISSUE TITLE
Does not work on socket.io localhost

### ISSUE THREAD

**Issue by pradeep99909** [amritb/socketio-client-tool#44]

**Comment by tajition** [comment]
Localhost connections works on my end. Try putting http:// in front of the url otherwise clone the repo and run it locally using any webserver. I use this to run it locally. **https://www.npmjs.com/package/ws**. I did have some trouble running the included http-server 

The socket server is using socket.io version 3.1.0

**Comment by amritb** [comment]
released v2 of this tool with a complete re-write. Please create new issues if you see any problem.

**Comment by pradeep99909** [comment]
> released v2 of this tool with a complete re-write. Please create new issues if you see any problem.

THANK YOU IT IS WORKING WITH V2
